rollouts:
  - name: part1
    filePattern: part1/**
    target: generated/part1
    duplicateHandling: 'queue'
    validateScript: |
      set -e
      cat <<EOF
      ```bash
      part1 ✅
      ```
      EOF
    waitDurations:
      - '5m'
      - '10m'
      - '15m'
