name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token: # change this
    required: true
    description: 'input description here'
    default: ''
  config-file: # change this
    required: false
    description: 'input description here'
    default: '.github/rollout.yaml'
  commit-message: # change this
    required: false
    description: 'input description here'
    default: 'chore: rollout'
  duplicate-handling: # change this
    required: false
    description: 'input description here'
    default: 'queue'
  title: # change this
    required: false
    description: 'input description here'
    default: 'Rollout {name}'
runs:
  using: 'node16'
  main: 'dist/index.js'
